export const nigeriaStates = [
  {
    state: "Kwara",
    lga: [
      "Asa",
      "Baruten",
      "Edu",
      "Ekiti",
      "Ifelodun",
      "Ilorin East",
      "Ilorin-south",
      "Ilorin-west",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke - Ero",
      "Oyun",
      "Patigi",
    ],
  },
  {
    state: "Kebbi",
    lga: [
      "Aliero",
      "Arewa",
      "Argungu",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/besse",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Wasagu/danko",
      "Yauri",
      "Zuru",
    ],
  },
  {
    state: "Kaduna",
    lga: [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Igabi",
      "Ikara",
      "Jaba",
      "JEMA'A",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria",
    ],
  },
  {
    state: "Ogun",
    lga: [
      "Abeokuta North",
      "Abeokuta South",
      "Ado Odo-ota",
      "Egbado North",
      "Egbado South",
      "Ewekoro",
      "Ifo",
      "Ijebu East",
      "Ijebu North",
      "Ijebu North East",
      "Ijebu Ode",
      "Ikenne",
      "Imeko/afon",
      "Ipokia",
      "Obafemi/owode",
      "Odeda",
      "Odogbolu",
      "Ogun Water Side",
      "Remo North",
      "Sagamu",
    ],
  },
  {
    state: "Niger",
    lga: [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edatti",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Magama",
      "Mariga",
      "Mashegu",
      "Mokwa",
      "Munya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi",
    ],
  },
  {
    state: "Bauchi",
    lga: [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Dambam",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/gadau",
      "JAMA'ARE",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki",
    ],
  },
  {
    state: "Delta",
    lga: [
      "Aniocha North",
      "Aniocha - South",
      "Bomadi",
      "Burutu",
      "Ethiope  East",
      "Ethiope  West",
      "Ika North- East",
      "Ika - South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili - North",
      "Oshimili - South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli North",
      "Ughelli South",
      "Ukwuani",
      "Uvwie",
      "Warri  North",
      "Warri South",
      "Warri South  West",
    ],
  },
  {
    state: "Gombe",
    lga: [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yalmaltu/ Deba",
    ],
  },
  {
    state: "Enugu",
    lga: [
      "Aninri",
      "Awgu",
      "Enugu East",
      "Enugu North",
      "Enugu South",
      "Ezeagu",
      "Igbo Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi Uzo",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Oji-river",
      "Udenu",
      "Udi",
      "Uzo-uwani",
    ],
  },
  {
    state: "Kogi",
    lga: [
      "Adavi",
      "Ajaokuta",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela/odolu",
      "Ijumu",
      "Kabba/bunu",
      "Kogi . K. K.",
      "Lokoja",
      "Mopa Moro",
      "Ofu",
      "Ogori Mangogo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West",
    ],
  },
  {
    state: "Lagos",
    lga: [
      "Agege",
      "Ajeromi/ifelodun",
      "Alimosho",
      "Amuwo-odofin",
      "Apapa",
      "Badagry",
      "Epe",
      "Eti-osa",
      "Ibeju/lekki",
      "Ifako-ijaye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Lagos Mainland",
      "Mushin",
      "Ojo",
      "Oshodi/isolo",
      "Somolu",
      "Surulere",
    ],
  },
  {
    state: "Benue",
    lga: [
      "Ado",
      "Agatu",
      "Apa",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Oju",
      "Ohimini",
      "Okpokwu",
      "Otukpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya",
    ],
  },
  {
    state: "Oyo",
    lga: [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North East",
      "Ibadan North West",
      "Ibadan South-east",
      "Ibadan South West",
      "Ibarapa Central",
      "Ibarapa East",
      "Ibarapa North",
      "Ido",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomoso North",
      "Ogbomoso South",
      "Ogo-oluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona-ara",
      "Oorelope",
      "Ori Ire",
      "Oyo East",
      "Oyo West",
      "Saki East",
      "Saki West",
      "Surulere",
    ],
  },
  {
    state: "Fct",
    lga: ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal"],
  },
  {
    state: "Abia",
    lga: [
      "Ikwuano",
      "Isiala Ngwa North",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obingwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa  West",
      "Umuahia North",
      "Umuahia  South",
      "Umu - Nneochi",
    ],
  },
  {
    state: "Plateau",
    lga: [
      "Jos North",
      "Barikin Ladi",
      "Bassa",
      "Bokkos",
      "Jos East",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang North",
      "Langtang South",
      "Mangu",
      "Mikang",
      "Pankshin",
      "QUA'AN PAN",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },
  {
    state: "Borno",
    lga: [
      "Abadam",
      "Askira / Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kala Balge",
      "Konduga",
      "Kukawa",
      "Kwaya / Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri M. C.",
      "Marte",
      "Mobbar",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani",
    ],
  },
  {
    state: "Ebonyi",
    lga: [
      "Abakaliki",
      "Afikpo North",
      "Afikpo  South",
      "Ebonyi",
      "Ezza North",
      "Ezza South",
      "Ikwo",
      "Ishielu",
      "Ivo",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha",
    ],
  },
  {
    state: "Adamawa",
    lga: [
      "Demsa",
      "Fufore",
      "Ganye",
      "Gire 1",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Lamurde",
      "Madagali",
      "Maiha",
      "Mayo - Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South",
    ],
  },
  {
    state: "Bayelsa",
    lga: ["Brass", "Ekeremor", "Kolokuma/opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"],
  },
  {
    state: "Akwa Ibom",
    lga: [
      "Abak",
      "Eastern Obolo",
      "Eket",
      "Esit Eket (uquo)",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono Ibom",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ikot Ekpene",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat Enin",
      "Nsit Atai",
      "Nsit Ibom",
      "Nsit Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Udung Uko",
      "Ukanafun",
      "Uruan",
      "Urue Offong/oruko",
      "Uyo",
    ],
  },
  {
    state: "Rivers",
    lga: [
      "Abua-odual",
      "Ahoada East",
      "Ahoada West",
      "Akuku Toru",
      "Andoni",
      "Asari-toru",
      "Bonny",
      "Degema",
      "Eleme",
      "Emohua",
      "Etche",
      "Gokana",
      "Ikwerre",
      "Khana",
      "Obio/akpor",
      "Ogba/egbema/ndoni",
      "Ogu/bolo",
      "Okrika",
      "Omuma",
      "Opobo/nekoro",
      "Oyigbo",
      "Port Harcourt",
      "Tai",
    ],
  },
  {
    state: "Imo",
    lga: [
      "Aboh Mbaise",
      "Ahiazu Mbaise",
      "Ehime Mbano",
      "Ezinihitte Mbaise",
      "Ideato North",
      "Ideato South",
      "Ihitte/uboma (isinweke)",
      "Ikeduru (iho)",
      "Isiala Mbano (umuelemai)",
      "Isu (umundugba)",
      "Mbaitoli (nwaorieubi)",
      "Ngor Okpala (umuneke)",
      "Njaba (nnenasa)",
      "Nkwerre",
      "Nwangele (onu-nwangele Amaigbo)",
      "Obowo (otoko)",
      "Oguta (oguta)",
      "Ohaji/egbema (mmahu-egbema)",
      "Okigwe  (okigwe)",
      "Onuimo (okwe)",
      "Orlu",
      "Orsu (awo Idemili)",
      "Oru-east",
      "Oru West (mgbidi)",
      "Owerri Municipal",
      "Owerri North (orie Uratta)",
      "Owerri West (umuguma)",
    ],
  },
  {
    state: "Ekiti",
    lga: [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti West",
      "Ekiti South West",
      "Emure",
      "Gbonyin",
      "Ido / Osi",
      "Ijero",
      "Ikere",
      "Ikole",
      "Ilejemeje",
      "Irepodun / Ifelodun",
      "Ise / Orun",
      "Moba",
      "Oye",
    ],
  },
  {
    state: "Osun",
    lga: [
      "Atakumosa East",
      "Atakumosa West",
      "Ayedaade",
      "Ayedire",
      "Boluwaduro",
      "Boripe",
      "Ede North",
      "Ede South",
      "Egbedore",
      "Ejigbo",
      "Ife Central",
      "Ifedayo",
      "Ife East",
      "Ifelodun",
      "Ife North",
      "Ife South",
      "Ila",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo-otin",
      "Ola-oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo",
    ],
  },
  {
    state: "Kano",
    lga: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Danbata",
      "Dawaki Kudu",
      "Dawaki Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun Malam",
      "Gaya",
      "Gezawa",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Sumaila",
      "Takai",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil",
    ],
  },
  {
    state: "Anambra",
    lga: [
      "Aguata",
      "Ayamelum",
      "Anambra East",
      "Anambra West",
      "Anaocha",
      "Awka North",
      "Awka South",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili-south",
      "Ihala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha-north",
      "Onitsha -south",
      "Orumba North",
      "Orumba  South",
      "Oyi",
    ],
  },
  {
    state: "Katsina",
    lga: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dandume",
      "Danja",
      "Dan Musa",
      "Daura",
      "Dutsi",
      "Dutsin-ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "MAI'ADUA",
      "Malufashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
  },
  {
    state: "Zamfara",
    lga: [
      "Anka",
      "Bakura",
      "Birnin Magaji",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata Mafara",
      "Tsafe",
      "Zurmi",
    ],
  },
  {
    state: "Ondo",
    lga: [
      "Akoko North East",
      "Akoko North West",
      "Akoko South East",
      "Akoko South West",
      "Akure North",
      "Akure South",
      "Ese-odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Ileoluji/okeigbo",
      "Irele",
      "Odigbo",
      "Okitipupa",
      "Ondo East",
      "Ondo West",
      "Ose",
      "Owo",
    ],
  },
  {
    state: "Cross River",
    lga: [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar Municipality",
      "Calabar South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakurr",
      "Yala",
    ],
  },
  {
    state: "Jigawa",
    lga: [
      "Auyo",
      "Babura",
      "Birnin Kudu",
      "Birniwa",
      "Buji",
      "Dutse",
      "Garki",
      "Gagarawa",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kaugama",
      "Kazaure",
      "Kirika Samma",
      "Kiyawa",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Ringim",
      "Roni",
      "Sule-tankarkar",
      "Taura",
      "Yankwashi",
    ],
  },
  {
    state: "Edo",
    lga: [
      "Akoko Edo",
      "Egor",
      "Esan Central",
      "Esan North East",
      "Esan South East",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako  West",
      "Igueben",
      "Ikpoba/okha",
      "Oredo",
      "Orhionmwon",
      "Ovia North East",
      "Ovia South West",
      "Owan East",
      "Owan West",
      "Uhunmwode",
    ],
  },
  {
    state: "Sokoto",
    lga: [
      "Binji",
      "Bodinga",
      "Dange/shuni",
      "Gada",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kware",
      "Kebbe",
      "Rabah",
      "S/birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamakko",
      "Wurno",
      "Yabo",
    ],
  },
  {
    state: "Taraba",
    lga: [
      "Ardo - Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim-lamido",
      "Kurmi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
  },
  {
    state: "Yobe",
    lga: [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasawa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    state: "Nasarawa",
    lga: [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Nasarawa",
      "Nasarawa Eggon",
      "Obi",
      "Toto",
      "Wamba",
    ],
  },
];
